#! /usr/bin/env fish

function bootstrap
    config_windows
    config_desktops
    config_wm
    config_rules

    # Kick off the other programs - systemd service files start most things.
    systemctl --user start bspwm.target

    run_hacks
end

function config_windows
    # Options are: longest_side, alternate, spiral.
    bspc config automatic_scheme            alternate

    bspc config border_width                1
    bspc config window_gap                  4

    # See desktop_rules for additional split_ratio config. We set to 0.69
    # initially because usually the first desktop we're interacting with is 1.
    bspc config split_ratio                 0.69
    bspc config focus_follows_pointer       true
    bspc config single_monocle              true
    bspc config borderless_monocle          true
    bspc config gapless_monocle             true
    bspc config removal_adjustment          true

    bspc config normal_border_color         '#3c3836'
    bspc config active_border_color         '#3c3836'
    bspc config focused_border_color        '#665c54'
    bspc config presel_feedback_color       '#fbf1c7'

    # Settings related to focus
    bspc config swallow_first_click         true
end

function config_desktops
    bspc config remove_unplugged_monitors   true
    bspc config remove_disabled_monitors    true

    bspc monitor DisplayPort-0 -d 1 2 3 4 7 8
    bspc monitor HDMI-A-0 -d 5 6

    # Subscribes to desktop events & does things.
    $HOME/.config/bspwm/desktop_rules &
end

function config_wm
    # Rearranging monitors to ensure they're the way we want things. They
    # are typically arranged in order by default, but we're just making sure
    # here.
    bspc wm -O DisplayPort-0 HDMI-A-0
end

function config_rules
    # Media desktop
    bspc rule -a 'Spotify' desktop='6'

    # Chrome desktop
    bspc rule -a 'Google-chrome' desktop='7' follow=on center=on border=off

    # Gaming...
    ## Launchers
    bspc rule -a 'Lutris' desktop='8' follow=on center=on
    bspc rule -a 'Battle.net.exe' desktop='8' follow=on center=on
    bspc rule -a 'Steam' desktop='8' follow=on center=on

    ## Games
    #

    # Everything else
    bspc rule -a 'Flameshot' state=floating sticky=on center=on
    bspc rule -a 'Ulauncher' state=floating sticky=on border=off
    bspc rule -a 'Nemo' state=floating center=on
    bspc rule -a 'Qalculate-gtk' flate=floating center=on
    bspc rule -a 'YaST2' flate=floating center=on
    bspc rule -a 'XTerm' flate=floating center=on

    # https://github.com/baskerville/bspwm/tree/master/examples/external_rules
    bspc config external_rules_command $HOME/.config/bspwm/external_rules
end

function run_hacks
    # JetBrains & Java hack - they don't recognise bspwm as a window manager.
    wmname LG3D &
end

bootstrap
