#! /usr/bin/env fish

function set_split_ratio -a desired_ratio
    set current_split_ratio (bspc config split_ratio)
    if test $current_split_ratio -ne $desired_ratio
        echo "Split ratio ($current_split_ratio) -ne $desired_ratio, setting to $desired_ratio..."
        bspc config split_ratio $desired_ratio
        echo "$desktop_id: $desktop_name config split_ratio $desired_ratio"
    else
        echo "Split ratio ($current_split_ratio) -eq $desired_ratio, leaving as is."
    end
end

# Subscribe to desktop events.
bspc subscribe desktop | while read -a msg
    set desktop_id $msg[3]
    set desktop_name (bspc query -D -d $desktop --names)

    if test "$desktop_name" = '2'; or test "$desktop_name" = '3'
        # These desktops / workspaces are for code editors.
        set_split_ratio 0.69
    else
        # Default value. Our preferred split_ratio most of the time.
        set_split_ratio 0.52
    end
end
