#! /usr/bin/env fish

function set_split_ratio -a desired_ratio
    set current_split_ratio (bspc config split_ratio)
    if test $current_split_ratio -ne $desired_ratio
        bspc config split_ratio $desired_ratio
    end
end

# Subscribe to desktop events.
bspc subscribe desktop | while read -a msg
    set desktop_id $msg[3]
    set desktop_name (bspc query -D -d $desktop --names)

    if test "$desktop_name" = '1'; or test "$desktop_name" = '2'
        # These desktops / workspaces are for code editors.
        set_split_ratio 0.69
    else
        # Default value. Our preferred split_ratio most of the time.
        set_split_ratio 0.52
    end
end
