[package]
edition = "2021"
name = "nedots"
version = "0.1.0"

[dependencies]
clap = { version = "3.1.6", features = [ "derive", "env" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
nix = "0.23"
chrono = "0.4"
